### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by fredj** [camptocamp/GeoFormAlchemy#1]
Hello,

Package GeoFormAlchemy failed to install:
    python setup.py sdist
    easy_install dist/GeoFormAlchemy-0.1.tar.gz
returns:
    Processing GeoFormAlchemy-0.1.tar.gz
    Running GeoFormAlchemy-0.1/setup.py -q bdist_egg --dist-dir /tmp/... 
    error: README.rst: No such file or directory

solution: create a MANIFEST.in file with:
    include README.rst

fredj

**Comment by fredj** [comment]
same issue with the package from http://pypi.python.org

**Comment by tsauerwein** [comment]
include readme file in source distribution archive, closed by fea4612399510b5ab42f884772f52eddaea4bf07

**Comment by tsauerwein** [comment]
Thanks Fred!
